apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    name: cpu-loader
  name: cpu-loader
spec:
  replicas: 3
  selector:
    matchLabels:
      name: cpu-loader
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        name: cpu-loader
    spec:
      containers:
      - image: nginx
        name: nginx
        resources: {}
status: {}
